menu rest init
AlexDubin/envision.team.project.mimino pull request #1
Opened 2023-02-18 17:43 UTC by Acidhouzee

секция меню, страницы ресоран

2023-02-18 18:09 UTC, SalOne22 requested changes
Пожалуйста обновите ветку для соответствием с новым main
GitHub desktop: main -> Fetch origin, kireev-menu-restaurant -> Branch -> Update from main

2023-02-18 22:35 UTC, Acidhouzee commented
я склонировал мейн после последнего коммита Саши, мне там нечего обновлять было...

2023-02-18 22:51 UTC, SalOne22 commented
Я проверил эту ветку через checkout и у тебя отсутствуют последние 3 коммита

2023-02-19 05:59 UTC, Acidhouzee commented
Checkout это команда что б ветки менять как ты мог ее проверить, я в гит
десктоп нажимаю fetch и у меня не просит никаких обновлений. Он пришел last
updates в ветке main

Вс, 19 февр. 2023 г. в 00:51, Vladyslav Vladinov ***@***.***>:

> Я проверил эту ветку через checkout и у тебя отсутствуют последние 3
> коммита
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AlexDubin/envision.team.project.mimino/pull/1#issuecomment-1435786152>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4OUA7RB5IQPO2SKZ5IAQDTWYFG7NANCNFSM6AAAAAAVAO6UDM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-19 09:21 UTC, SalOne22 reviewed
Перепишите список меню используя ul

2023-02-19 09:27 UTC, AlexDubin approved these changes

2023-02-19 09:27 UTC, merged